name: Run_UnitTest

on:
  push:
    branches: [ "master" ]

jobs:
  unit-test:
        name: Run unit tests on push in main
        runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
                 distribution: 'zulu'
                 java-version: 17
         - name: Run unit tests
            run: ./gradlew test
